{{- if .Values.operator.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "chartmuseum.fullname" . }}-operator
rules:
- apiGroups:
  - cm.bitnami.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "chartmuseum.fullname" . }}-operator

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-cm-operator
subjects:
- kind: ServiceAccount
  name: {{ include "chartmuseum.fullname" . }}-operator
roleRef:
  kind: Role
  name: {{ include "chartmuseum.fullname" . }}-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
